config/routes.rb
Rails.application.routes.draw do

get 'residences/global'
resources :residences  do
  resources :comments 
end
  root 'residences#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :residence
    belongs_to :user 
end

app/models/residence.rb
class Residence < ApplicationRecord
    mount_uploader :video, VideoUploader
    
    mount_uploader :image, VimeoUploader

    mount_uploader :vimeo_file, VimeoUploader

    belongs_to :user
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord

  has_many :residences, dependent: :destroy
  has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    
         DISTRICTS = ['Select-District/Village','Gongore-Centre', 'Gongore-Aindai', 'Popodara','Kourou', 'Poukou']
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

    before_action :configure_permitted_parameters, if: :devise_controller?

		

	protected
		def configure_permitted_parameters
			devise_parameter_sanitizer.permit(:sign_up, keys: [:username,:firstname,:lastname,:birthdate,:country, :district,:gender])
			devise_parameter_sanitizer.permit(:account_update, keys: [:username,:firstname,:lastname,:birthdate,:country, :district,:gender])
		end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController 
    
    def create
        @res = Residence.find(params[:residence_id])
        @comment = @res.comments.create(params.require(:residence).permit(:name,:content,:user_id))
        redirect_to residence_path(@res)
    end
    def destroy 
        @post = Residence.find(params[:residence_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to residence_path(@post)
    end

end

app/controllers/residences_controller.rb
class ResidencesController < ApplicationController
    def index 
        @posts = Residence.all 
        @users = User.all
    end
    def global
        @users = User.all
    end

    def new 
       
        @res = Residence.new 
    end
    def create
    @user = current_user.id
     @res = Residence.new(
         image: params[:residence][:image],
         vimeo_file: params[:residence][:vimeo_file],
         title: params[:residence][:title],
         post: params[:residence][:post],
         user_id: @user
     )
         if @res.save
            redirect_to residences_path 
         else
            render 'new'
         end

    end
    def show 
       @res = Residence.find(params[:id]) 
    end

    def edit
        @res = Residence.find(params[:id])    
    end

    def update
        @user = current_user.id
 
        res = Residence.find(params[:id]) 
        res.update(
            image: params[:residence][:image],
            vimeo_file: params[:residence][:vimeo_file],
            title: params[:residence][:title],
            post: params[:residence][:post],
            user_id: @user
        )
        
        
          redirect_to residences_path    
    end
 

    private
    def residence_params
        params.require(:residence).permit(:image, :vimeo_file, :user_id, :title, :post)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/residences_helper.rb
module ResidencesHelper
end

app/views/comments/_comment.html.erb
<%= comment.name %>
<%= comment.content %>
<%= time_ago_in_words(comment.created_at) %>

app/views/comments/_form.html.erb
<%= form_with(model: @res, url: residence_comments_path(@res), method: :post) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name   %>
  </div>
  </div>

  <%= f.label :content %> <br>
  <%= f.text_field :content  %>
  </div>
  </div>
   <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.submit  %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark bg-primary">
<%= link_to 'Home', residences_path, class:'nav' %> 
<%= link_to 'Create Post ', new_residence_path, class:'nav' %>
 <%= link_to 'Users', residences_global_path, class:'nav' %>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Passionpro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<%= render 'layouts/navbar' %>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
    <%= yield %>
  </body>
</html>

app/views/residences/_form.html.erb
<div class="container">
<p><%= form_with(model: @res) do |f| %></p>
<%=f.label :About %> <br>
<p><%=f.text_field :title %> </p><br>
<%= f.label :Post %> <br>
<p><%= f.text_area :post, placeholder: 'share your post' %></p> <br>
<%= f.label :upload_Photo %> <br>
<%= f.file_field :image %> <br />
<%= f.label :upload_Video %> <br>
<%= f.file_field :vimeo_file %> <br>
<p><%= f.submit 'upload' %></p> <br>
<% end %>

</div>

app/views/residences/edit.html.erb
<%= form_with(model: @res,  method: :put) do |f| %>
<%=f.label :About %> <br>
<%=f.text_field :title %> <br>
<%= f.label :Post %> <br>
<%= f.text_area :post, placeholder: 'share your post' %> <br>
<%= f.label :upload_photo %> <br>
<%= f.file_field :image %> <br />
<%= f.label :upload_vimeo %> <br>
<%= f.file_field :vimeo_file %> <br />

<%= f.submit 'upload' %>
<% end %>

app/views/residences/global.html.erb
<div class="container">

<% @users.each do |user| %>
<p> <strong> Name:</strong> <%= user.firstname %>  <%= user.lastname %> </p> <br>
<p><strong>Gender:</strong> <%= user.gender %></p> <br>
<p><strong>Username:</strong> <%=user.username %></p> <br>
<p><strong> Residence Country :</strong><%= user.country%></p> <br>
<p><strong>District:</strong> <%= user.district %> </p>
<hr>
<%end %>

</div>

app/views/residences/index.html.erb
<div class="container">
<% @posts.each do |post|%>
 <p> <strong>User: </strong> <%= post.user.username %> </p><br>
   <p> <strong> About: </strong><%= post.title %> </p><br>
  <p><strong>Post:</strong> <%= post.post %> </p><br>
  <p>Development image</p> <br>
   <%= image_tag(post.image_url.to_s, :size => "220x220") %> <br>
   <p>Development Video </p> <br>
 <%= video_tag([post.vimeo_file], :size => "320x240", :autoplay => true, :loop => true, controls: '') %> <br>
   <%= link_to 'leave a thought', residence_path(post) %> <br>
   <%link_to 'edit post', edit_residence_path(post) %>

<%end%>

</div>

app/views/residences/new.html.erb
<%= render 'form' %>

app/views/residences/show.html.erb
<div class="container">
   <%= @res.title %> <br>
   <%= @res.post %> <br>
   <%= image_tag(@res.image_url.to_s, :size => "220x220") %> <br>
 <%= video_tag([@res.vimeo_file], :size => "320x240", :autoplay => true, :loop => true, controls: '') %>
    <%= render @res.comments %>
    
    <%= form_with(model: @res, url: residence_comments_path(@res), method: :post) do |f| %>
        <%= f.label :name %> <br>
        <%= f.text_field :name   %> <br>

        <%= f.label :content %> <br>
        <%= f.text_field :content  %> <br>

        <%= f.hidden_field :user_id, :value => current_user.id %>
        <%= f.submit "Create Comment" %> <br>
        <% end %>

        </div>